"""Ports (hexagon boundary). Repo is sync on purpose: each use case write is one
block without awaits, so it is atomic on the asyncio loop (in-memory MVP)."""
from collections.abc import AsyncIterator
from datetime import datetime
from typing import Protocol

from app.domain.enums import FeatureKey
from app.domain.osm import OsmPoint
from app.domain.recommend import Intent
from app.domain.route import RoutePath
from app.domain.model import (
    GeoPoint,
    GeocodeHit,
    FeatureStateRecord,
    GoogleIdentity,
    ImageAnalysis,
    Observation,
    OwnershipRequest,
    Photo,
    Place,
    QueueItem,
    Report,
    Session,
    User,
)


class StaleData(Exception):
    """F29: another worker committed since this cache was loaded; the write was dropped — retry."""


class Repo(Protocol):
    def clear(self) -> None: ...
    def reload_if_stale(self) -> bool:
        """F29: reload when another worker committed; True = reloaded (memory: always False)."""
        ...
    def commit(self) -> None:
        """Persist changes (no-op in memory). Called after each write request. Raises StaleData on a race."""
        ...
    def is_empty(self) -> bool: ...
    def all_ids(self) -> list[str]: ...

    # users / sessions
    def add_user(self, user: User) -> None: ...
    def get_user(self, user_id: str) -> User | None: ...
    def find_user_by_username(self, username: str) -> User | None: ...
    def find_user_by_google_sub(self, sub: str) -> User | None: ...
    def add_session(self, session: Session) -> None: ...
    def get_session(self, token: str) -> Session | None: ...
    def delete_session(self, token: str) -> None: ...

    # places / states
    def add_place(self, place: Place) -> None: ...
    def get_place(self, place_id: str) -> Place | None: ...
    def list_places(self) -> list[Place]: ...
    def delete_place(self, place_id: str) -> None: ...
    def save_state(self, state: FeatureStateRecord) -> None: ...
    def states_for(self, place_id: str) -> dict[FeatureKey, FeatureStateRecord]: ...

    # observations / reports / photos
    def add_observation(self, obs: Observation) -> None: ...
    def get_observation(self, obs_id: str) -> Observation | None: ...
    def list_observations(self, place_id: str, feature: FeatureKey | None = None) -> list[Observation]: ...
    def add_report(self, report: Report) -> None: ...
    def get_report(self, report_id: str) -> Report | None: ...
    def list_reports(self) -> list[Report]: ...
    def add_photo(self, photo: Photo) -> None: ...
    def get_photo(self, photo_id: str) -> Photo | None: ...

    # moderation queue
    def add_queue_item(self, item: QueueItem) -> None: ...
    def get_queue_item(self, item_id: str) -> QueueItem | None: ...
    def list_queue_items(self) -> list[QueueItem]: ...
    def find_open_queue_item(self, place_id: str, feature: FeatureKey) -> QueueItem | None:  # pending conflict
        ...

    # ownership requests
    def add_ownership_request(self, req: OwnershipRequest) -> None: ...
    def get_ownership_request(self, req_id: str) -> OwnershipRequest | None: ...
    def list_ownership_requests(self) -> list[OwnershipRequest]: ...


class Clock(Protocol):
    def now(self) -> datetime: ...


class IdGenerator(Protocol):
    def new(self, prefix: str) -> str: ...
    def reset(self) -> None: ...
    def observe(self, existing_id: str) -> None:
        """Advance counters past an id loaded from storage."""
        ...


class FileStorage(Protocol):
    async def save(self, chunks: AsyncIterator[bytes], name: str) -> tuple[str, str]:
        """Store bytes under name → (path, public url)."""
        ...


class VisionAnalyzer(Protocol):
    async def analyze(self, image_path: str, original_name: str) -> ImageAnalysis:
        """Raise on failure; FallbackVisionAnalyzer turns failures into the mock answer."""
        ...


class OsmSource(Protocol):
    async def fetch(self) -> list[OsmPoint]: ...


class WalkingRouter(Protocol):
    async def walk(self, a: GeoPoint, b: GeoPoint) -> RoutePath | None:
        """Walking path; None = no route; raise on failure (use case falls back to the straight line)."""
        ...


class QueryInterpreter(Protocol):
    model: str

    async def interpret(self, query: str) -> Intent:
        """Query → needs + filters only (never facts). Raise on failure → rules."""
        ...


class Geocoder(Protocol):
    async def search(self, q: str) -> list[GeocodeHit]:
        """Raise on failure; the use case falls back to the local index."""
        ...


class IdentityVerifier(Protocol):
    async def verify(self, id_token: str) -> GoogleIdentity:
        """Raise Unauthorized when the token is invalid."""
        ...
